# we should be able to get rid of this line when https://github.com/golang/dep/issues/1799 gets fixed
required = ["gopkg.in/fsnotify.v1"]

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/guardian"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/commandrunner"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[constraint]]
  revision ="c11f84a56e43e20a78cee75a7c034031ecf57d1f"
  name = "golang.org/x/sys"

[[constraint]]
  name = "code.cloudfoundry.org/lager"
  branch = "master"

# we should be able to get rid of this line when https://github.com/golang/dep/issues/1799 gets fixed
[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true
